# Generated by Django 5.2.7 on 2025-11-24 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Parisina', '0002_remove_proveedor_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='decoracion',
            name='unidad',
            field=models.CharField(choices=[('metro', 'Metro'), ('par', 'Par'), ('paquete', 'Paquete'), ('unidad', 'Unidad'), ('kit', 'Kit'), ('litro', 'Litro')], default='unidad', max_length=20),
        ),
        migrations.AddField(
            model_name='hogar',
            name='unidad',
            field=models.CharField(choices=[('metro', 'Metro'), ('par', 'Par'), ('paquete', 'Paquete'), ('unidad', 'Unidad'), ('kit', 'Kit'), ('litro', 'Litro')], default='unidad', max_length=20),
        ),
        migrations.AddField(
            model_name='merceriamanualidad',
            name='unidad',
            field=models.CharField(choices=[('metro', 'Metro'), ('par', 'Par'), ('paquete', 'Paquete'), ('unidad', 'Unidad'), ('kit', 'Kit'), ('litro', 'Litro')], default='unidad', max_length=20),
        ),
        migrations.AddField(
            model_name='telas',
            name='unidad',
            field=models.CharField(choices=[('metro', 'Metro'), ('par', 'Par'), ('paquete', 'Paquete'), ('unidad', 'Unidad'), ('kit', 'Kit'), ('litro', 'Litro')], default='unidad', max_length=20),
        ),
    ]
